### ISSUE TITLE
Moving conductors

### ISSUE THREAD

**Issue by lgomez** [restify/conductor#32]
Hi,

Thank you all for all the work on this.

I've been working on dynamic route definitions and would like to give conductor a try. Essentially I need to be able to add, remove routes or swap handler stacks for an existing route. I've tried doing something along the lines of:

``` javascript
    // Adding a dynamic route
    server['get']({
      name: 'uniqueName',
      path: '/some/route/path',
    }, [handlerA, handlerB, handlerC]);

    // Detecting, say, a delete in the db then doing...
    server.rm(endpoint.name);

    // Later perhaps another change comes in with the same path but different handlers
    server['get']({
      name: 'uniqueName', // this often is the same as before (ie: editing handlers)
      path: '/some/route/path', // this often is the same as before (ie: editing handlers)
    }, [handlerX, handlerY, handlerZ]); // note these are different handlers
```

In Restify (not using conductor yet) I'm inspecting `server.routes` and I DO see the effect of removing a route. The problem is I get the following when I try `curl -is "http://localhost:8080/some/route/path"`:

``` bash
/Users/lgomez/Projects/proxy/node_modules/restify/lib/plugins/audit.js:102
            req_id: req.getId(),
                        ^

TypeError: req.getId is not a function
    at Server.audit (/Users/lgomez/Projects/proxy/node_modules/restify/lib/plugins/audit.js:102:25)
    at emitThree (events.js:97:13)
    at Server.emit (events.js:175:7)
    at emitRouteError (/Users/lgomez/Projects/proxy/node_modules/restify/lib/server.js:202:16)
    at onRoute (/Users/lgomez/Projects/proxy/node_modules/restify/lib/server.js:762:17)
    at Router.find (/Users/lgomez/Projects/proxy/node_modules/restify/lib/router.js:419:9)
    at Server._route (/Users/lgomez/Projects/proxy/node_modules/restify/lib/server.js:747:21)
    at routeAndRun (/Users/lgomez/Projects/proxy/node_modules/restify/lib/server.js:705:14)
    at Server._handle (/Users/lgomez/Projects/proxy/node_modules/restify/lib/server.js:725:9)
    at Server.onRequest (/Users/lgomez/Projects/proxy/node_modules/restify/lib/server.js:326:14)
```

The only way I have been able to avoid that error is by restarting the server but that will not be an option in prod.

So, in the readme for Conductor I see one of the goals being to decouple the handler stacks from the routes themselves. If Conductor can help, how would you remove a route completely or, even better, replace it?

Thank you!

**Comment by lgomez** [comment]
Just in case, using your **Basic Usage** > [Handlers](https://github.com/restify/conductor#handlers) example, I'd like to know how to do something like this (pseudocode):

``` javascript
// set it...
rc.get('/foo', simpleConductor, server);
// replace it...
rc.get('/foo', anotherConductor, server);
```

And to completely remove it... Not sure how...

``` javascript
// null?
rc.get('/foo', null, server);
// through restify?
server.rm('/foo'); // I think it'd be the name actually
```

I've been reading the code, tests and examples but didn't catch an answer.

Thanks again.

**Comment by micahr** [comment]
You can pass the same object as the first parameter to `rc.get` that you are passing to `server.get`.

``` javascript
rc.get({
        name: 'main', 
        path: '/main'
    }, 
    mainConductor, 
    server
);

// then rm
server.rm('main');
```

Without seeing more of your code I couldn't comment on why the audit logger was dying on that particular line, but it sounds like the request object isn't initialized.

**Comment by lgomez** [comment]
Thank you.

I just tried that and still see the same crash happening. Here's one you should be able to try. I removed a bunch of code that's not relevant but did test this and the same happens:

``` javascript
var log = require('./lib/logger'); // Vanilla bunyan logger
var restify = require('restify');
var rc = require('restify-conductor');

var server = restify.createServer({ log: log });

server.on('after', restify.auditLogger({ log: log, body: true }));

// For the record, the server on mount event does not fire when
// mounting with conductor. I believe this is expected.
server.router.on('mount', function(method, path, types, versions){
  process.nextTick(function () {
    log.info({ route: server.router.mounts });
  });
});

// This conductor is the same from your readme
var simpleConductor = rc.createConductor({
    name: 'simpleConductor',
    handlers: [
        function render(req, res, next) {
            res.send(200, 'hello world!');
            return next();
        }
    ]
});
rc.get({ name: 'foo1', path: '/foo' }, simpleConductor, server);

log.info('Starting server...');
server.listen(8080, function () {
  log.info('Server Ready.');
  log.info('calling: curl -is "http://localhost:8080/foo" will NOT CRASH the server.');
});

setTimeout(function(){
  log.info('removing foo1');
  server.rm('foo1');
  log.info('calling: curl -is "http://localhost:8080/foo" will CRASH the server.');
}, 5000);

setTimeout(function(){
  log.info('adding foo2');
  rc.get({ name: 'foo2', path: '/foo' }, simpleConductor, server);
  log.info('calling: curl -is "http://localhost:8080/foo" will still CRASH the server.');
}, 10000);
```

For the record, this is what I get:

``` bash
/Users/lgomez/Projects/proxy/node_modules/restify/lib/plugins/audit.js:102
            req_id: req.getId(),
                        ^

TypeError: req.getId is not a function
    at Server.audit (/Users/lgomez/Projects/proxy/node_modules/restify/lib/plugins/audit.js:102:25)
    at emitThree (events.js:97:13)
    at Server.emit (events.js:175:7)
    at emitRouteError (/Users/lgomez/Projects/proxy/node_modules/restify/lib/server.js:202:16)
    at onRoute (/Users/lgomez/Projects/proxy/node_modules/restify/lib/server.js:762:17)
    at Router.find (/Users/lgomez/Projects/proxy/node_modules/restify/lib/router.js:419:9)
    at Server._route (/Users/lgomez/Projects/proxy/node_modules/restify/lib/server.js:747:21)
    at routeAndRun (/Users/lgomez/Projects/proxy/node_modules/restify/lib/server.js:705:14)
    at Server._handle (/Users/lgomez/Projects/proxy/node_modules/restify/lib/server.js:725:9)
    at Server.onRequest (/Users/lgomez/Projects/proxy/node_modules/restify/lib/server.js:326:14)
```

I'll keep investigating.

Thank you very much.

**Comment by lgomez** [comment]
Oh! I just noticed another thing...

If you try the same but comment out the audit logger you'll see that the first setting of the route responds as expected (`Hello world!`), when deleted it again responds as expected (`ResourceNotFound`) but after adding it again it continues to respond with the `ResourceNotFound` error. It does NOT crash the server though.

**Comment by micahr** [comment]
Looks like the issue is that the old route (which was removed) is still cached inside the LRU Cache (`server.router.cache`). If you clear out the cache (`server.router.cache.reset()`) at the same time as you call `server.rm` you should no longer get the error.

This seems to be a bug in the `server.rm` method. Thank you for finding and reporting this!

**Comment by lgomez** [comment]
@micahr Thank you. That was it. I added the following to my implementation and it did the trick.

``` javascript
server.router.cache.forEach(function (value, key, cache) {
  if (value.name === change.id) {
    cache.del(key);
  }
});
server.rm(change.id);
```

I've also added an initial (and incomplete) PR to contribute a patch here: restify/node-restify#1016

Thanks again.
